cx-flow:
   enabled-vulnerability-scanners:
     - cxgo

cxgo:
  client-secret: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.L-xbjOuo6S58X-svfQchwEjOURdQDOKgWWdX72dvCIcqYdh6ypU_p8ta8kv0ftSDc2yA5drWKx8xsFvrDg4PmSS_D4nIOyduRWzgXVTrE0_i3FvDWrnCE-Us9isAcl3NRYQEK_Aql_1Oc2zVmVGDbosBbAbQ6S2p26YIj1WRro2fC4ygGyTWLt9HUFwyJP-Vq9OcmLGzWeIRrFsxxH-C_y6gVmXxQCJkQI6mgz2lfU7yzWnJoLOjmtnwmML3gpIY4M4JnviEqcuScnKRSrm4MY-a0EsEJIXqFWBc5gCF2KjioBWx7EuXbQl7CMweH7oLz65GzSc0K1VPBv-k7ErUBw.en3j5qHh91b4wb50.3jUMS-BM-TBefLfUtT7CrSWT5zOvZa-GAGAVDrKC1YM8ub2PzLtnbmf92Q5_bYRK99HV6POq51cYe9HW3lZ4Jn4m4Gkek7VxXaV4URKfvbWPtvhjEWv9kZvPtgXAfSaGJ1SgcfPn877sgf1ye3_5iLGqo9wJTLj7IK2sgSD_RSWEFcuNIMXywm45FsI4m_K4F32hnvFxcEFX75e9ZLC0p24aW1JKyB5Uf7R5jd49oJ7OOvMxa7lCfKzW9gVsloA7IIOYojMu2XWOsiafoDSfNanVMtT6cjM97qUDtDKcc5KbWsu8jWIWuFvAaw6_AsF3JKpiMtE99DTNPsXNLj9I2fa-ZU-A-eV4wbr6LkVlmtorKo8rrX0tc8bRZDctQcnd_Fl7xT0_abb71lbObEhxT92XCzqKVLIb9bVM4eSAue-H-eXXWHyYxl1dfJw9wPpPE5XG1Gy7aPaGXVqlbyHg7II1xC3m8_XFGWiZPij6_kZjTOO80scBXzVhr7SKj3tndOp2cZJeLe9HDf3flM0OzILWCxe6LmWk8HypMN3rr-S3J1Kzn8oPu2dapFZWW6oA9B2yFtS-ZwVf_UPHg6zhEmkZtc_V-IQGBOPt3SEeTddBw8SR1Vs_Xg-t8rYiPE0wdxoiqO6-U_tt47CH1RTKv9Vfpl-DJocC-bMzhlPPlNCuYHR7LlcDJ3AmOEaq0FPD9-UEfjvAeKLnHeYrqTwJ8T-T6nc5YwJ8GViGbIOYrO9KybSNFEfbP4sPNQBx_Q_Ji7hEKHZmbIxnSTw3Zly1lutFVCbRZMN4ebbXGeArXHnMvMZTSOQK0xM8cQpse2ZPntfvDD6fTqh1ZbdoKt45jF12IDdFd6p8jf-EjiTUhOpZffrdabsvsGpVGL_RNbC9Td65ssVyMvZWrawDirhuVwMNR0-JUglnr8IUAAOHrs4a9Jwexn89opqQytmSLbJPGyatjgnmcXCAoyqFg9FtidMJnqH9raOfUIRpuWpRhPWe_6M-GEZQgRjZ71Zy0UU7txRbbOMfRNvSgCv3yVnMOtt84dnkPtsdy6K7kZH8nS7QV4G-YZL1WZVRdp5A2ALVx4r415GpuVxbQ4rNTeeG45rL_HMqqOW3LFbVH9e_9L6xjZGwew32FTB3ILwKJ5BRKg5Cx621afLvP2-3cdWCpyEph_MEFrDF0KdH-oREDHXh_WvMz-HLriy3Fek4b1d4jDbZj9NpVYgBPVEsShsf5OarbqiVBytXJ0rrj0asP80vlonwAEjI9TolLI00joPhiOkFzYrAi1KEmlW0WMo.F1mlenGfkxQ5O_w9s_bcmA:2kouih5fpp63ck9kudm4v13d9u
  base-url: https://api.checkmarx.net
  portal-url: https://cloud.checkmarx.net
  # CxGo Business unit that will contain the project/application/scan
  team: \Cx NA Team\Miguel Gonzalez
  url: ${cxgo.base-url}
  multi-tenant: false
  configuration: Default Configuration
  #
  ## Available Scan defaults
  #
  #   - CXOD_MOBILE_NATIVE = 1;
  #   - CXOD_MOBILE_WEB_BASED = 2;
  #   - CXOD_DESKTOP_NATIVE = 3;
  #   - CXOD_DESKTOP_WEB = 4;
  #   - CXOD_API = 5;
  #   - CXOD_FRONTEND = 6;
  #   - CXOD_BACKEND = 7;
  #   - CXOD_LAMBDA = 8;
  #   - CXOD_CLI = 9;
  #   - CXOD_SERVICE = 10;
  #   - CXOD_SMART_DEVICE = 11;
  #   - CXOD_OTHER = 12;
  scan-preset: 1,2,3,4,5,9
