cx-flow:
   enabled-vulnerability-scanners:
     - cxgo

cxgo:
  client-secret: eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.qC0azIUUY9ezeV4jns_shwcAOo6IiAoY4obKDcjnxgnY9jEpiKmVnm3-oddCVUs8celGLh3X9aWtoyk12UHXboDWKUtpu6cN_fU2ADSxB4hV-20Mfg-gpR3HfjkWnlGB_VEnc5-A3tyxuMswqjMM8p8RvG4DOr3sRh77kiZyab_9IglgqVxxZtzr6Ym_yHIZ6V3stRiVtzAHvV80e_bw2v9BPs8PeNV1CjX0xIxWgxkgTpr3ZlBqsTKHgofMzrK9TbdkIpV9VAHtZbfCl4WyVuzLWEPUj_na_gbfT5AqyQaZjwgrD4foT8hsa40DCTYCcgM4tjITQnzBVtru9RKQbw.ECvNsQ2wvsmOLTg_.ZAu5uvYmeCSRO6Tbs9nYWHh_ISTXcIZx_ihKBP36-y9SWgaObyzRj9Y4ae_hEWbD-BP_RZ1-SkUIwuilyrTGHPEsQriv6V95dnab6gvG0hEgMzq_vk0Ro4BhXd1DwltlQX0dTZ7r1vPkSQgE6AP0gM3A3LfPQZDES8kZoAYJARfTYfCj4Rd7gjL-UEWAmlt9DojatIwukMf7GmNLdpiRzWURCU1MbFNzqIARFUAPIDBN17PLRP2kmU8Fti8YavmxPAP38G2QyZ46px50RYuMbZ7Y1h5KsKd43pNTV-zMoxQ7fxOY5So1O7-p1oq_i16M4x-ny_VhiB2ivUE2R9qNchg0xE9-lquu88FbvGx3J0PMC6v1l_vJhxIMjMkAV8y5VX6P9u0vrrER_WYTHCFslCz3dnZZaxapz1gYtcyIK4eyUhl5XF5bjXbAoCHUkeCfc0lsgMphQhy7bRsMG0qW-bxaRQAiylHD265zYRH4eJTeLn3X4MPj1NBgs5P8U0AtbvRxSn44sn9Wo8vmErHiASYbXOQlr1Msh53R8AXEuLGGPvQjqHs5PVrpw76_Zg8pt_PMP3xXQjdBLxqgsZrSqrKGLOGxGlZWSU8FBKBxmtetXgU3sZ7rFBsqed-ujOexfbua-Jc41dsLloASbPzElpxKNUJSgADGS0mMBJgWgtOEIlWZ1OCvaE2fDNd08lwD4FvKCe6zYBY1ikne3Aw2s-M5KHnN3--_3zeUBlcfiFtMzZDv0K1UPATETZ-Npz_tAr7pTRMD26IumPfDRMMZib4Qr9prGfyeWjouJbwrFtSwU5DDqQ8uDfay06OJ2FahTQUSWTO38x841UCQ0nYlSbYPzP0mS-VZWqf3ZIPvKuKc3uj3ZS02IzSGcODVvH8PwUHpABAT2mpeXi5MNMZyEDGak_D0LWrbnI6PGPeUc3NDJi1ip5Lwfu-JKJBiJ8UhtjtXieXVs6BTRH6lcTp3rsk7aX41b79Zf5yQqHtiVGZZJ4k604rku6PMzJcNQa8Os0sZS6do6R_IBhdJLJMZ_j32LZiz5Tu2mSigXz9sAGDba5AM4_cO6ZbjU-aGc5mq6Z3v_xiE5GK1r-b4MT8JYl7WEF_wg4gODK1o7Tb4DnJocAW6foZWm-G5NPfJ1bcwZdYbrg4JeFYFfG258Oo20POWGVI9JdsTZCmEwnErYYjENFRWTGk2qJ88ziA8Wx2YGM6fB0mFC3vLn2g8TmteaSz168FCoO6h6qVvswPyzq0uhd8g4Yp3IRmTe-Wfe4_8MjGwgBMS74SW-9PDJrU.u1XNd-T_HnGQpAFgMaoe1Q:2kouih5fpp63ck9kudm4v13d9u
  base-url: https://api.checkmarx.net
  portal-url: https://cloud.checkmarx.net
  # CxGo Business unit that will contain the project/application/scan
  team: \Cx NA Team\Miguel Gonzalez\
  url: ${cxgo.base-url}
  multi-tenant: false
  configuration: Default Configuration
  #
  ## Available Scan defaults
  #
  #   - CXOD_MOBILE_NATIVE = 1;
  #   - CXOD_MOBILE_WEB_BASED = 2;
  #   - CXOD_DESKTOP_NATIVE = 3;
  #   - CXOD_DESKTOP_WEB = 4;
  #   - CXOD_API = 5;
  #   - CXOD_FRONTEND = 6;
  #   - CXOD_BACKEND = 7;
  #   - CXOD_LAMBDA = 8;
  #   - CXOD_CLI = 9;
  #   - CXOD_SERVICE = 10;
  #   - CXOD_SMART_DEVICE = 11;
  #   - CXOD_OTHER = 12;
  scan-preset: 1,2,3,4,5,9
